[package]
name = "pocketvoxel-iphone4s"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["staticlib"]

[dependencies]
libm = "0.2"
pocketvoxel-core = { path = "../pocketvoxel-core", default-features = false, features = ["libm"] }

[workspace]

[profile.release]
panic = "abort"
opt-level = "s"
codegen-units = 1
lto = true
